### ISSUE TITLE
rejected share for 500 internal server error

### ISSUE THREAD

**Issue by Zhell1** [yours-org/pow20-miner#3]
What is the cause of getting this error from the API, which happens often:

> ❌ rejected share: "{\"statusCode\":500,\"message\":\"Internal server error\"}"

Does it mean that the solution found is invalid ? or just that the server had an internal bug and we should retry sending the solution ?

note: I tried to implement a retry mechanism but it didn't seem to help

**Comment by Zhell1** [comment]
also getting a lot of "invalid solution"

> found share: Solution { nonce: "02f67600efd3323f", hash: "0000000220d52af541e59fc2a80a53312c473190d1f9d1af7189beb1f02a674d", location: "44b7446295c58d01caf3b8b18f46966e7344f860564205669c2fb96069d14947_0", token_id: "21311a17-cfa8-44ca-9585-a56df6da4e81" }
> submit share: Object {
>     "bsvContractLocation": String("44b7446295c58d01caf3b8b18f46966e7344f860564205669c2fb96069d14947_0"),
>     "nonce": String("02f67600efd3323f"),
>     "tokenId": String("21311a17-cfa8-44ca-9585-a56df6da4e81"),
>     "winningHash": String("0000000220d52af541e59fc2a80a53312c473190d1f9d1af7189beb1f02a674d"),
> }
> ❌ rejected share: "{\"statusCode\":400,\"message\":\"Invalid solution\",\"error\":\"Bad Request\"}"

**Comment by utxo-detective** [comment]
`Invalid solution` happens when you loose the race against other miners. `Internal server error` is an issue w/ the pow20 api indexing the current location of the contract. Devs know and are working on it

**Comment by Zhell1** [comment]
ok, thanks for the explanation, closing this and waiting for the api devs to fix it
