### ISSUE TITLE
rejected share internal server error

### ISSUE THREAD

**Issue by mboyd1** [yours-org/pow20-miner#6]
share submission failing for me:

> [60038787] found solution! submitting... submit solution
>         nonce: "17580a008f87de25"
>         hash: "000000067846c81e6ff7dfa915b837dc8399edc8a89693cc3f7aeba0d51b631e"
>         location: "f22346baf6a10008599d44972bb7097e7654277ac0be8ef6fa067ce987870360_0"
>         challenge: "60038787e97c06faf68ebec07a2754767e09b72b97449d590800a1f6ba4623f2"
> [60038787] ❌ rejected share "{\"statusCode\":500,\"message\":\"Internal server error\"}"

**Comment by Zhell1** [comment]
@utxo-detective answered already in [this issue](https://github.com/yours-org/pow20-miner/issues/3#issuecomment-1975623337):

> Internal server error is an issue w/ the pow20 api indexing the current location of the contract. Devs know and are working on it

so it looks like we can't do much except report to pow20.io support
